# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.2.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix]
  - id: pretty-format-ini
    args: [--autofix]
- repo: https://github.com/pycqa/isort
  rev: 5.10.1
  hooks:
  - id: isort
    name: isort (python)
    args: [--profile=black]
    exclude: examples/.*.py
- repo: https://github.com/psf/black
  rev: 22.1.0
  hooks:
  - id: black
    exclude: examples/.*.py
- repo: https://github.com/Lucas-C/pre-commit-hooks-markup
  rev: v1.0.1
  hooks:
  - id: rst-linter
- repo: local
  hooks:
  - id: pyflakes
    name: pyflakes
    entry: tox -e pyflakes
    language: system
    types: [python]
  - id: pylint
    name: pylint
    entry: tox -e pylint
    language: system
    types: [python]
